# Generated by Django 3.1 on 2020-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_novedad_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='id_youtube',
            field=models.TextField(blank=True, null=True),
        ),
    ]
