# Generated by Django 3.1 on 2020-09-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_novedad_id_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedad',
            old_name='id_youtube',
            new_name='link_youtube',
        ),
    ]
