# Generated by Django 3.1 on 2020-09-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0001_initial_manual'),
        ('novedades', '0006_auto_20200917_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='estrellas',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='star_ratings.foo'),
        ),
    ]
