# Generated by Django 3.1 on 2020-09-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0009_auto_20200924_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(upload_to='novedades'),
        ),
    ]
