# Generated by Django 3.1 on 2020-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0002_auto_20200903_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popups',
            name='imagen',
            field=models.ImageField(upload_to='static/img/popups'),
        ),
    ]
