# Generated by Django 3.1 on 2020-09-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0003_auto_20200903_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popups',
            name='imagen',
            field=models.ImageField(upload_to='media/popups'),
        ),
    ]
