# Generated by Django 3.1 on 2020-09-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0004_auto_20200924_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popups',
            name='imagen',
            field=models.ImageField(upload_to='popups'),
        ),
    ]
